import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { access, readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import test from "node:test";
const read = file => readFile(new URL("../" + file, import.meta.url));
const sha = bytes => createHash("sha256").update(bytes).digest("hex");
test("Initial private stress guard failure retains genuine large-source qualification and zero conversion claims", async () => {
  const proof = JSON.parse(await read("evidence/2026-10-10T08-11-02-597Z-aiff-id3-sync-opfs-stress.json"));
  assert.equal(proof.status, "failed-or-incomplete-private-stress"); assert.match(proof.failure, /Private stress child exit 1/);
  assert.equal(proof.fixture.bytes, 140922233); assert.equal(proof.fixture.durationSeconds, 800);
  assert.equal(proof.fixture.sha256, "cd5b778644222d68e391fcbbe3c4845c6872cab92b7726d85437e7720590fdee");
  assert.equal(proof.fixture.decodedPcmSha256, "0a7c4781b220b2d06fc42201618bdce6ea12ccce9fd6ed570de999baafe4e7ff");
  assert.equal(proof.fixture.probe.streams.filter(stream => stream.disposition?.attached_pic === 1).length, 1);
  assert.equal(proof.reportSummary, null); assert.equal(proof.helperProof, null); assert.equal(proof.publicAcceptance, false);
  assert.equal(proof.assetsRestored, true); assert.equal(proof.ownedRuntimeRemoved, true);
  assert.equal(proof.runner.absence.status, "owned-identity-absent"); await assert.rejects(access(proof.ownedRuntime), { code: "ENOENT" });
  const gzip = await read(proof.executedSource.path), restored = gunzipSync(gzip);
  assert.equal(sha(gzip), proof.executedSource.sha256); assert.equal(sha(restored), proof.recipeGeneratedSha256);
  assert.equal(restored.length, proof.executedSource.restoredBytes);
  const source = restored.toString();
  assert.ok(source.includes('assertInside(path.resolve(projectRoot, "outputs"), reportRoot)'));
  assert.ok(source.includes('const reportRoot = "H:\\\\Github Repositories\\\\fileconverter\\\\work\\\\aiff-id3-stress-BF2uQo";'));
  assert.ok(source.indexOf('assertInside(path.resolve(projectRoot, "outputs"), reportRoot)') < source.indexOf("  serverProcess = spawn("));
});
test("Corrected-path stress terminated before converter navigation with objectively unstable blank samples and exact cleanup", async () => {
  const proof = JSON.parse(await read("evidence/2026-10-10T08-12-27-536Z-aiff-id3-sync-opfs-stress.json"));
  const analysis = JSON.parse(await read("evidence/aiff-id3-stress-baseline-analysis-2026-10-10.json"));
  assert.equal(proof.reportSummary.passed, false); assert.equal(proof.reportSummary.blankBaseline.stable, false);
  assert.equal(proof.reportSummary.loadedIdle, null); assert.deepEqual(proof.reportSummary.runs, []);
  assert.match(proof.reportSummary.failure.message, /Blank Chromium private-memory baseline/);
  assert.equal(analysis.sampleCount, 19); assert.equal(analysis.lastFiveSpreadBytes, 19922944);
  assert.ok(analysis.lastFiveSpreadBytes > analysis.lastFiveAllowedSpreadBytes);
  assert.equal(analysis.stableWindowResult, null); assert.equal(analysis.browserConversionsPerformed, 0);
  assert.equal(proof.assetsRestored, true); assert.equal(proof.ownedRawReportsRemoved, true);
  await assert.rejects(access(proof.ownedRuntime), { code: "ENOENT" });
  await assert.rejects(access(proof.helperProof.runtime), { code: "ENOENT" });
  for (const row of proof.helperProof.launches) assert.equal(row.absence.status, "owned-identity-absent");
});
test("Large browser conversion completed before the outdated exclusion count failed validation; no repeat/public claim", async () => {
  const proof = JSON.parse(await read("evidence/2026-10-10T08-16-11-647Z-aiff-id3-sync-opfs-stress.json"));
  assert.equal(proof.status, "failed-or-incomplete-private-stress"); assert.equal(proof.reportSummary.passed, false);
  assert.equal(proof.reportSummary.blankBaseline.stable, true); assert.equal(proof.reportSummary.loadedIdle.stable, true);
  assert.deepEqual(proof.reportSummary.runs, []); assert.match(proof.reportSummary.failure.message, /excluded subtitle and attachment/);
  const entry = proof.retainedReports.find(row => row.path.endsWith(".json.gz")), gzip = await read(entry.path), bytes = gunzipSync(gzip);
  assert.equal(sha(gzip), entry.sha256); assert.equal(sha(bytes), entry.restoredSha256);
  const raw = JSON.parse(bytes); assert.equal(raw.lastObservedState.jobState, "complete");
  assert.equal(raw.lastObservedState.metrics.outputBytes, 153600760); assert.equal(raw.lastObservedState.metrics.peakWasmMemoryBytes, 16777216);
  assert.equal(raw.lastObservedState.metrics.queuedBytes, 0); assert.equal(raw.lastObservedState.metrics.pendingOperations, 0);
  assert.deepEqual(raw.lastObservedState.warnings, []);
  const executed = gunzipSync(await read(proof.executedSource.path)).toString();
  assert.equal(sha(executed), proof.recipeGeneratedSha256);
  assert.ok(executed.includes("mp3Output || flacOutput || aiffOutput"));
  assert.ok(executed.includes("source.artwork && (mp3Output || flacOutput) ? 1 : 0;"));
  assert.ok(executed.indexOf("probe.withinArtworkValidation =") < executed.indexOf("The browser did not explicitly disclose excluded subtitle"));
  assert.equal(proof.publicAcceptance, false); assert.equal(proof.assetsRestored, true); assert.equal(proof.ownedRuntimeRemoved, true);
  for (const row of proof.helperProof.launches) assert.equal(row.absence.status, "owned-identity-absent");
  await assert.rejects(access(proof.ownedRuntime), { code: "ENOENT" });
});
