import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { vaaCpuHotspot } from "../scripts/lib/vaa-cpu-hotspot.mjs";
import { summarizeCpuProfile } from "../scripts/lib/cpu-profile-summary.mjs";

const sha = (bytes) => createHash("sha256").update(bytes).digest("hex");
const read = (file) => readFile(new URL(`../${file}`, import.meta.url));
const evidence = JSON.parse(await read("evidence/h264-vaa-cpu-comparison-2026-10-04.json"));
test("full-node VAA diagnostic aggregation does not reverse rejected end-to-end speed evidence", async () => {
  const baseline = await read(evidence.baseline.path), speedTrial = await read(evidence.precedingSpeedTrial.path);
  assert.equal(sha(baseline), evidence.baseline.evidenceSha256);
  assert.equal(sha(speedTrial), evidence.precedingSpeedTrial.sha256);
  assert.deepEqual(vaaCpuHotspot(JSON.parse(baseline).rawCpuProfile.profile), evidence.comparison.before);
  assert.deepEqual(vaaCpuHotspot(evidence.rawCpuProfile.profile), evidence.comparison.after);
  assert.deepEqual(summarizeCpuProfile(evidence.rawCpuProfile.profile), evidence.report.cpuDiagnostic.summary);
  assert.equal(evidence.comparison.after.samples, 9432);
  assert.ok(evidence.comparison.after.targetSelf.fractionOfSampledWindow < evidence.comparison.before.targetSelf.fractionOfSampledWindow);
  assert.equal(evidence.comparison.perFrameCostVerified, false);
  assert.equal(evidence.comparison.causalEndToEndSpeedupVerified, false);
  assert.equal(evidence.precedingSpeedTrial.accepted, false);
  assert.equal(evidence.precedingSpeedTrial.measuredSpeedupFraction, JSON.parse(speedTrial).comparison.measuredSpeedupFraction);
  assert.ok(evidence.precedingSpeedTrial.measuredSpeedupFraction < 0);
  assert.equal(evidence.publicAcceptance, false); assert.equal(evidence.publicProfilesChanged, false);
  assert.equal(evidence.speedGainClaim, null);
  for (const [file, hash] of Object.entries(evidence.currentSources)) assert.equal(sha(await read(file)), hash, file);
});
test("instrumented SIMD evidence retains true output, primary whole-tree memory, bounds and cleanup", () => {
  const report = evidence.report, run = report.runs[0], validation = run.independentValidation;
  assert.equal(report.requestedRunCount, 1); assert.equal(report.cpuEnabled, true);
  assert.equal(report.source.bytes, 105000218);
  assert.equal(validation.outputBytes, 19137689);
  assert.equal(validation.outputSha256, "a77bd1fb023a1a3072966d74f173c0c6010eccea689e67b346e29baca3c3a636");
  assert.equal(validation.fullDecodePassed, true);
  assert.equal(validation.outputFrameTimes.length, 1800);
  assert.ok(validation.outputFrameTimes.every((value, i) => Math.abs(value - report.source.frameTimes[i]) <= 0.001));
  assert.deepEqual(validation.audioPacketHashes, report.source.audioPacketHashes);
  assert.ok(validation.ordinalSsim >= 0.98);
  const samples = report.samples.filter((s) => ["pre-conversion-1", "conversion-1"].includes(s.phase) && Number.isFinite(s.privateBytes) && s.privateBytes > 0);
  assert.equal(Math.max(...samples.map((s) => s.privateBytes)), run.peakPrivateBytes);
  assert.equal(run.incrementalPrivateMiB, (run.peakPrivateBytes - report.blankBaseline.privateBytes) / 1048576);
  assert.ok(run.incrementalPrivateMiB <= 250);
  const m = run.state.metrics;
  assert.equal(m.peakWasmMemoryBytes, 33554432);
  assert.ok(m.maxReadChunkBytes <= 262144 && m.maxWriteChunkBytes <= 262144 && m.peakQueuedBytes <= 262144 && m.peakPendingOperations <= 1);
  assert.equal(m.queuedBytes, 0); assert.equal(m.pendingOperations, 0);
  assert.deepEqual(report.forbiddenRequests, []);
  assert.deepEqual(run.cleanup.opfsRemainingEntries, []);
  assert.equal(evidence.cleanup.repositoryLocalFixtureOutputsProfileAndTempRemoved, true);
  assert.equal(evidence.cleanup.generatedDistRestored, true);
});
