#!/usr/bin/env bash
set -euo pipefail

# Rebuild one published XZ Wasm variant with an already-activated, pinned
# Emscripten SDK. Temporary /src and /out symlinks preserve the canonical build
# paths while every downloaded or generated byte remains repository-local.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORK_ROOT="${PROJECT_ROOT}/work"
VARIANT="${1:-}"
KEEP_OUTPUT="${WITHIN_KEEP_NONDOCKER_OUTPUT:-0}"
MINIMUM_FREE_KIB="${WITHIN_MINIMUM_BUILD_FREE_KIB:-1048576}"

XZ_VERSION=5.8.3
XZ_SHA256=fff1ffcf2b0da84d308a14de513a1aa23d4e9aa3464d17e64b9714bfdd0bbfb6

case "${VARIANT}" in
  full)
    ENGINE_ID=xz
    ;;
  decoder)
    ENGINE_ID=xz-decoder
    ;;
  *)
    printf 'Usage: %s full|decoder\n' "$0" >&2
    exit 2
    ;;
esac

BUILD_ROOT="${WORK_ROOT}/${ENGINE_ID}-nondocker-build"
OUTPUT_ROOT="${WORK_ROOT}/${ENGINE_ID}-nondocker-output"
EXPECTED_ROOT="${PROJECT_ROOT}/public/engines/${ENGINE_ID}"
BUILD_ROOT_CREATED=0
OUTPUT_ROOT_CREATED=0

fail() {
  printf '%s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command is unavailable: $1"
}

run_privileged() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

assert_work_path() {
  case "$1" in
    "${WORK_ROOT}"/*) ;;
    *) fail "Refusing non-repository build path: $1" ;;
  esac
}

remove_owned_symlink() {
  local link_path="$1"
  local expected_target="$2"
  if [[ -L "${link_path}" ]]; then
    local actual_target
    actual_target="$(readlink -f "${link_path}")"
    if [[ "${actual_target}" == "${expected_target}" ]]; then
      run_privileged unlink "${link_path}"
    else
      printf 'Leaving unexpected symlink untouched: %s -> %s\n' \
        "${link_path}" "${actual_target}" >&2
    fi
  fi
}

cleanup() {
  local status=$?
  remove_owned_symlink /src "${BUILD_ROOT}"
  remove_owned_symlink /out "${OUTPUT_ROOT}"
  if [[ "${BUILD_ROOT_CREATED}" == "1" ]]; then
    rm -rf -- "${BUILD_ROOT}"
  fi
  if [[ "${OUTPUT_ROOT_CREATED}" == "1" && "${KEEP_OUTPUT}" != "1" ]]; then
    rm -rf -- "${OUTPUT_ROOT}"
  fi
  exit "${status}"
}
trap cleanup EXIT INT TERM

[[ "$(uname -s)" == "Linux" ]] ||
  fail "The non-Docker XZ reproduction path currently requires Linux."
if [[ -n "${EMSDK_NODE:-}" ]]; then
  [[ -x "${EMSDK_NODE}" ]] ||
    fail "EMSDK_NODE does not identify an executable: ${EMSDK_NODE}"
  export PATH="$(dirname "${EMSDK_NODE}"):${PATH}"
fi
for command_name in \
    emcc emconfigure emmake curl tar sha256sum diff sed readlink awk find sort \
    xargs df nproc make; do
  require_command "${command_name}"
done
if [[ "$(id -u)" != "0" ]]; then
  require_command sudo
fi

assert_work_path "${BUILD_ROOT}"
assert_work_path "${OUTPUT_ROOT}"
[[ ! -e "${BUILD_ROOT}" ]] || fail "Build directory already exists: ${BUILD_ROOT}"
[[ ! -e "${OUTPUT_ROOT}" ]] || fail "Output directory already exists: ${OUTPUT_ROOT}"
[[ ! -e /src && ! -L /src ]] || fail "Refusing to replace existing /src"
[[ ! -e /out && ! -L /out ]] || fail "Refusing to replace existing /out"

mkdir -p "${WORK_ROOT}" "${BUILD_ROOT}"
BUILD_ROOT_CREATED=1
mkdir -p "${OUTPUT_ROOT}"
OUTPUT_ROOT_CREATED=1
available_kib="$(df -Pk "${WORK_ROOT}" | awk 'NR == 2 { print $4 }')"
[[ "${available_kib}" =~ ^[0-9]+$ ]] || fail "Could not determine free disk space."
(( available_kib >= MINIMUM_FREE_KIB )) ||
  fail "XZ rebuild needs at least ${MINIMUM_FREE_KIB} KiB free; ${available_kib} KiB is available."

run_privileged ln -s "${BUILD_ROOT}" /src
run_privileged ln -s "${OUTPUT_ROOT}" /out
cp "${SCRIPT_DIR}/within_xz.c" "${BUILD_ROOT}/within_xz.c"
cp "${SCRIPT_DIR}/build.sh" "${BUILD_ROOT}/build.sh"
chmod +x "${BUILD_ROOT}/build.sh"

cd "${BUILD_ROOT}"
curl --fail --location --retry 3 \
  "https://github.com/tukaani-project/xz/releases/download/v${XZ_VERSION}/xz-${XZ_VERSION}.tar.xz" \
  --output xz.tar.xz
printf '%s  %s\n' "${XZ_SHA256}" xz.tar.xz |
  sha256sum --check --strict
tar --extract --file xz.tar.xz
mv "xz-${XZ_VERSION}" xz
rm -- xz.tar.xz
XZ_VARIANT="${VARIANT}" ./build.sh

if ! diff --recursive --brief --no-dereference \
    "${EXPECTED_ROOT}" "${OUTPUT_ROOT}"; then
  printf 'Expected artifact hashes:\n' >&2
  (
    cd "${EXPECTED_ROOT}"
    find . -type f -print0 | sort -z | xargs -0 sha256sum
  ) >&2
  printf 'Rebuilt artifact hashes:\n' >&2
  (
    cd "${OUTPUT_ROOT}"
    find . -type f -print0 | sort -z | xargs -0 sha256sum
  ) >&2
  fail "Non-Docker ${ENGINE_ID} artifacts differ from the published engine."
fi
printf 'Exact non-Docker %s artifact comparison passed.\n' "${ENGINE_ID}"
